site_name: Canvas Learning Journal
site_url: https://djplaner.github.io/canvas-learning-journal/
repo_url: https://github.com/djplaner/canvas-learning-journal/
edit_uri: edit/main/docs
site_author: David Jones
site_description: Design and management student learning journals using Canvas groups and discussion topics

theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        title: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-4
        title: Switch to dark mode
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features: 
    - navigation.tabs
    - navigation.instant
    - navigation.footer
    #    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.sections
    - content.tabs.link
    - header.autohide
    - search.suggest
    - announce.dismiss

plugins:
  - search
  - privacy:
      log_level: debug

extra_css:
  - stylesheets/extra.css


markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - md_in_html
  - tables
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Getting Started:
    - Requirements: getting-started/requirements.md
    - Install: getting-started/install.md
    - Use: getting-started/use.md
  - Demonstration: 
    - Overview: demonstration/index.md
    - Learning design: demonstration/learning-design.md
    - End result:
      - Student view: demonstration/end-result/student-view.md
      - Teacher view: demonstration/end-result/teacher-view.md
    - Implementation: 
      - Overview: demonstration/implementation/index.md
      - Groupset: demonstration/implementation/groupset.md
      - Discussion topics: demonstration/implementation/discussion-topics.md
      - Learning environment: demonstration/implementation/learning-environment.md
  - Reference: 
    - Overview: reference/index.md
    - Conceptual: 
      - Overview: reference/conceptual/index.md
      - Mapping to Canvas: reference/conceptual/mapping-to-canvas.md
    - Software: 
      - Overview: reference/software/index.md
      - Everyone: reference/software/everyone/index.md
      - Groupset: reference/software/groupset/index.md
      - Shared: reference/software/shared.md
  - Development:
    - Overview: development/index.md
    - Why: 
      - Benefits of Learning Journals: development/why/benefits-of-learning-journals.md
      - Limitations of Canvas: development/why/limitations-of-canvas.md
