site_name: Canvas Learning Journal

theme:
  name: material
  palette:
    primary: green
    accent: light green
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
